version:

services:
    web:
        image: matias27112002/web1
        ports:
            - 680:80
        volumes:
            - 

#docker run -d -v ./web/file:/usr/share/nginx/html/file -p 680:80 web1

